### ISSUE TITLE
Cant retrieve image data from camera on android

### ISSUE THREAD

**Issue by Mercotui** [derpicated/articated#3]
the function `qvideoframe.map()` segfaults on android
https://bugreports.qt.io/browse/QTBUG-47934

**Comment by petersupan** [comment]
This is due to the fact, that the QVideoframe on Android is just a wrapper around an Opengl Texture id. 
[https://bugreports.qt.io/browse/QTBUG-47934](https://bugreports.qt.io/browse/QTBUG-47934).

You have two possibilities: 
* Call videoframe->getHandle() to get the Opengl texture id. Render this texture on any Framebuffer or PBO and read it back and you have the raw pixel data [http://stackoverflow.com/questions/36648816/android-opengl-es-read-texture-pixels](http://stackoverflow.com/questions/36648816/android-opengl-es-read-texture-pixels)
* Use QVideoProbe [http://doc.qt.io/qt-5/qvideoprobe.html#details](http://doc.qt.io/qt-5/qvideoprobe.html#details). I have never used it but it appears in the bug report.

I always worked around somehow (doing all computer vision in OpenCL instead to avoid the readback, like in the [qmlvideofilter_opencl](http://code.qt.io/cgit/qt/qtmultimedia.git/tree/examples/multimedia/video/qmlvideofilter_opencl/main.cpp) example), but it would be nice it "map()" would just work...

**Comment by Mercotui** [comment]
Hi, thank you for your input!
I came to a similar conclusion.
And since at large resolutions the current vision algorithms actually bottlenecks on the CPU, I'm going with offloading it to the GPU. Although not with OpenCL, but with an OpenGL compute shader, since I'm already learning this API, and it seems perfectly fit for computer vision.

Now I just need to allocate the time to implement it

**Comment by Mercotui** [comment]
As of 92535e2394254497199b0a532f119f50dd19c007, the camera reading on android works, using an [Pixel Buffer Object](https://www.khronos.org/opengl/wiki/Pixel_Buffer_Object).
Albeit a bit slow, combined with the CPU vision algorithms and HD images, a bit very slow.

leaving open as enhancement request

**Comment by Mercotui** [comment]
Looking at how I changed this issue in April this year, I completely shifted the focus.
The original issue was fixed, and therefore I'm reverting the title to the original issue, and closing it.

Progress on the enhancement "Add GPU vision processing" will be tracked at: #15
